### PR TITLE
Updating to latest angular version

### PR DESCRIPTION
**Pull request by joanofdart**
Might as well help by updating this package dependencies along with other goodies.
Some things are missing? perhaps removing tslint and whatnot but the critical aspect of what is needed, has been updated.

@ABenassi87 please take a look, thanks.

### CODE REVIEW

**Comment by wojo1086** [comment]
Can we please get this reviewed?

**Comment by ABenassi87** [comment]
@joanofdart thank you so much for this PR. I was very busy with some stuff. I will take a look this weekend and if all is good, I will release a new version next week. Thank you so much for your contribution.

**Comment by swedishcodemonkey** [comment]
I too would much appreciate this PR. I have tested it locally without issues.

**Comment by joanofdart** [comment]
lets wait for @ABenassi87 to give it the thumbs up :)

**Comment by swedishcodemonkey** [comment]
Absolutely! Just tried to be helpful 🙂

**Comment by joanofdart** [comment]
@ABenassi87 just wondering what is it taking this long? :D People want/need this and I have no idea why its being delayed this much.

**Comment by miccou** [comment]
@ABenassi87 any update on this? Would be great to use this with newer versions of Angular

**Review by mkrijtenberg — APPROVED** [review]

**Comment by vishalbiradar** [comment]
It's been 3-4 months still the PR is open.
@ABenassi87 
It will be great if you can have version and backward compatibility with angular.

**Review by sh977218 — APPROVED** [review]
This looks good. Anyone else is reviewing this PR? Let's do that and upgrade this repo!

**Comment by NZE** [comment]
@ABenassi87 would you like to add a few more core maintainers so we can help to resolve this issue?

**Comment by SimonCropp** [comment]
@ABenassi87 or make it a paid project so you can afford to work on it

**Comment by sh977218** [comment]
@joanofdart Hi, I saw you forked this repo. Would you want to publish that under a different name? I can help keep that repo up-to-date as Angular version updates.

**Comment by joanofdart** [comment]
> @joanofdart Hi, I saw you forked this repo. Would you want to publish that under a different name? I can help keep that repo up-to-date as Angular version updates.

I could probably instead create a new one and base it off @ABenassi87 's work 
Could be a fun project. Let's see how many thumb ups do I get 👀

**Comment by miccou** [comment]
I support creating a new fork under an organisation, so we can have several contributors and hopefully avoid a situation where the package gets outdated in the future. 

Happy to help as a contributor if that happens.

**Comment by ABenassi87** [comment]
Hi there, I will review this PR, and I will merge it. Please, wait until the weekend. Thank you!

**Comment by ABenassi87** [comment]
General question, what angular versions do you need to support? only the last one or some previous version?

**Comment by ABenassi87** [comment]
I just started from scratch in this branch: https://github.com/ABenassi87/ngx-text-diff/tree/angular-v14

**Comment by sh977218** [comment]
@ABenassi87 Hi, thanks for the updates. Are you able to publish angular-v14 to npm, maybe like under "14.0.0" so it can sync with Angular version.

**Comment by filflora** [comment]
@ABenassi87 Hi, could you please merge this? I really started to like this component and I need to update my project to Angular V14.

**Comment by chiafeng888** [comment]
@ABenassi87 Hi, thanks for the updates. Are you able to publish angular-v14 to npm any time soon?

**Pull request closed without merging**
